---
- name: install zsh for not MacOS
  become: yes
  package:
    name: zsh
    state: latest

- name: change shell to zsh
  become: yes
  user:
    name: "{{ ansible_env['USER'] }}"
    shell: /bin/zsh

- name: copy .custom_sh to home directory
  copy:
    src: custom_sh
    dest: ~/.custom_sh

- name: include custom_sh in users .zshrc
  lineinfile:
    path: ~/.zshrc
    state: present
    line: . ~/.custom_sh
