---
- name: install zsh
  become: yes
  package:
    name: zsh
    state: latest

- name: clone oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh.git
    dest: ~/.oh-my-zsh

- name: create new zsh configuration file
  template:
    src: zshrc.zsh-template.j2
    dest: ~/.zshrc
  when: zsh_rewrite_config

- name: change shell to zsh
  become: yes
  user:
    name: "{{ ansible_env['USER'] }}"
    shell: /bin/zsh
