---
- name: dev deploy hass
  block:
    # fix this (always - changed)
    - name: deploy dev code
      synchronize:
        src: "{{ hass_dev_code_path }}"
        dest: "{{ hass_project_path }}"
      notify:
        - restart hass

    - name: fix owner
      file:
        path: "{{ hass_project_path }}"
        owner: "{{ hass_user }}"
        group: "{{ hass_user }}"
        recurse: yes
  when: hass_dev_code_path is not none
  tags: hass-dev-deploy
