---
- name: apt update && upgrade
  become: yes
  apt:
    update_cache: yes
    upgrade: full

- name: stop hass
  become: yes
  systemd:
    name: home-assistant@homeassistant.service
    state: stopped

- name: start hass
  become: yes
  systemd:
    name: home-assistant@homeassistant.service
    state: started
