---
- name: install GPG key
  become: yes
  apt_key:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    state: present

- name: add apt repository
  become: yes
  apt_repository:
    repo: deb https://download.sublimetext.com/ apt/stable/
    state: present

- name: install sublime text
  become: yes
  package:
    name: sublime-text
    state: latest

- name: copy preferences
  copy:
    src: Preferences.sublime-settings
    dest: ~/.config/sublime-text-3/Packages/User/Preferences.sublime-settings
  when: sublime_rewrite_config
