---
- name: install GPG key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add apt repository
  become: yes
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: install docker
  become: yes
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - docker-ce
    - docker-compose

- name: ensure group "docker" exists
  group:
    name: docker
    state: present

- name: add currenct user to docker group
  become: yes
  user:
    name: "{{ ansible_env['USER'] }}"
    groups: docker
    append: yes
